linuxdeepin/dde-clipboard

- dde-clipboard-daemon/plugin/dde-clipboard-loader/src/wayland_copy_client.cpp
- dde-clipboard-daemon/plugin/dde-clipboard-manager/src/waylandcopyclient.cpp
指针未释放
Log: 修复内存泄露问题
Influence: 内存泄露
Bug: https://pms.uniontech.com/bug-view-144763.html
Change-Id: Ic1dcf1da6fe5a6bf9e180afa1a6d455c606b5b41
> fix: 修复内存泄露问题

- CMakeLists.txt
- dde-clipboard-daemon/plugin/dde-clipboard-loader/src/clipboard_loader.cpp
- dde-clipboard-daemon/plugin/dde-clipboard-loader/src/clipboard_loader.h
- dde-clipboard-daemon/plugin/dde-clipboard-loader/src/wayland_copy_client.cpp
- dde-clipboard-daemon/plugin/dde-clipboard-loader/src/wayland_copy_client.h
- dde-clipboard-daemon/plugin/dde-clipboard-manager/clipboard_manager_plugin.cpp
- dde-clipboard-daemon/plugin/dde-clipboard-manager/src/waylandcopyclient.cpp
- dde-clipboard-daemon/plugin/dde-clipboard-manager/src/waylandcopyclient.h
- tests/kf5_wayland_test.cc
兼容Debian仓库高版本libkf5wayland-dev编译
Log: 兼容Debian仓库高版本libkf5wayland-dev编译
Change-Id: Icc8c29f5c8609e94ea50ee6a063ad2a38e5f9b54
> chore: Compatible with high version libkf5wayland-dev compilation

- translations/dde-clipboard_fr.ts
更新翻译
Log: 更新翻译
Task: https://pms.uniontech.com/task-view-202033.html
Influence: 翻译
Change-Id: I63e9606ca639c0928a2ef8aa8fffdd3578750415
> chore: 更新翻译

- .reuse/dep5
- CMakeLists.txt
- dbus/types/brightnessmap.cpp
- dbus/types/brightnessmap.h
- dbus/types/dockrect.cpp
- dbus/types/dockrect.h
- dbus/types/reflectlist.cpp
- dbus/types/reflectlist.h
- dbus/types/resolution.cpp
- dbus/types/resolution.h
- dbus/types/resolutionlist.cpp
- dbus/types/resolutionlist.h
- dbus/types/rotationlist.cpp
- dbus/types/rotationlist.h
- dbus/types/screenrect.cpp
- dbus/types/screenrect.h
- dbus/types/touchscreeninfolist.cpp
- dbus/types/touchscreeninfolist.h
- dbus/types/touchscreeninfolist_v2.cpp
- dbus/types/touchscreeninfolist_v2.h
- dbus/types/touchscreenmap.cpp
- dbus/types/touchscreenmap.h
- dde-clipboard-daemon/clipboarddaemon.cpp
- dde-clipboard-daemon/clipboarddaemon.h
- dde-clipboard-daemon/clipboardloader.cpp
- dde-clipboard-daemon/main.cpp
- debian/control
> chore: fix merge error

- .tx/config
- .tx/deepin.conf
- debian/changelog
Changelog
* ensure compliant with REUSE spec.
> chore: bump version to 6.0.3

- debian/changelog
* release dde-clipboard 1:6.0.4
Log:
> chore: bump version to 1:6.0.4

- CMakeLists.txt
Log: use GNUInstallDirs in CmakeLists
> chore: use GNUInstallDirs in CmakeLists

- dde-clipboard/listview.cpp
Correct a typo in listview.cpp
> chore: correct a typo in listview.cpp

- .gitignore
- CMakeLists.txt
- dde-clipboard/pixmaplabel.cpp
- tests/kf5_wayland_test.cc
> Fix cmake , include the change of dtk, and use dwayland instead

- CMakeLists.txt
- dde-clipboard-daemon/readpipedatatask.h
- dde-clipboard-daemon/waylandcopyclient.cpp
- dde-clipboard-daemon/waylandcopyclient.h
- debian/rules
resolve: https://github.com/linuxdeepin/developer-center/issues/4718
> feat: allow wayland

- dde-clipboard/iconbutton.cpp
- dde-clipboard/itemdelegate.cpp
- dde-clipboard/listview.cpp
- dde-clipboard/pixmaplabel.cpp
support show text in dynamic
resolve: https://github.com/linuxdeepin/developer-center/issues/4599
Log: dynamictext
> feat(textui): dynamic text height

- dde-clipboard-daemon/waylandcopyclient.cpp
- dde-clipboard-daemon/waylandcopyclient.h
the code mix copy and paste event together, and this bring some bugs
Log:
> fix: not copy text after receive new data

- dde-clipboard-daemon/readpipedatatask.cpp
- dde-clipboard-daemon/readpipedatatask.h
- dde-clipboard-daemon/waylandcopyclient.cpp
- dde-clipboard-daemon/waylandcopyclient.h
sometimes the pipeline will be blocked, so here mv the pipeline read to QtCurrent runtime, when next request is in , close the pipeline
Log:
> chore: force to stop pipeline when next request in

- dde-clipboard/mainwindow.cpp
- dde-clipboard/mainwindow.h
Log:
https://github.com/linuxdeepin/developer-center/issues/4924
> feat(alpha): allow transparancy follow appearance

- misc/dde-clipboard.service.in
> fix: start before startdde

- dde-clipboard/main.cpp
- dde-clipboard/mainwindow.cpp
- dde-clipboard/mainwindow.h
- tests/dde-clipboard/ut_mainwindow.cpp
since dde-clipboardloader is not exist anymore, so remove the logic here
Log:
> chore: there is not bin named dde-clipboardloader

- dde-clipboard-daemon/clipboardloader.cpp
> chore: move cache path to XDG_CACHE_DIR

- dde-clipboard/main.cpp
> fix: icon is vage when zoom is not 1x

- dde-clipboard/main.cpp
- dde-clipboard/mainwindow.cpp
- dde-clipboard/mainwindow.h
> chore: add commandline option

- dde-clipboard/constants.h
- dde-clipboard/itemdata.cpp
- dde-clipboard/itemdata.h
> fix: wrong caculate for new line

- debian/changelog
> chore: bump version

- .clang-format
- .reuse/dep5
- dde-clipboard/constants.h
- dde-clipboard/pixmaplabel.cpp
> fix: when line is min than 4, it elided

- dde-clipboard-daemon/clipboardloader.cpp
add "text/uri-list" format to support drag and drop image
`mimedata` 中有 `text/uri-list` 就支持图片拖拽到浏览器和（企业）微信了
- https://github.com/linuxdeepin/developer-center/issues/8415
> feat: support drag and drop image

- debian/changelog
release 1:6.0.9
Log: bump version to 1:6.0.9
> chore: bump version to 1:6.0.9

- dde-clipboard/mainwindow.cpp
- dde-clipboard/mainwindow.h
adjust Inner border and outer border
Issue: linuxdeepin/developer-center#8342
> fix: border color issue

- debian/changelog
release 1:6.0.11
Log: release 1:6.0.11
> chore: bump version to 1:6.0.11

- debian/changelog
bump version to 1:6.0.12
Log: bump version to 1:6.0.12
> chore: bump version to 1:6.0.12

- debian/changelog
release 1:6.0.13
Log: bump version to 1:6.0.13
> chore: bump version to 1:6.0.13

- debian/changelog
> chore: bump version to 1:6.0.14

- CMakeLists.txt
- dde-clipboard-daemon/wlrintegration/dwaylandmimedata.h
- dde-clipboard-daemon/wlrintegration/waylandclientextensiontemplate.h
- dde-clipboard-daemon/wlrintegration/wlrdatacontrolclipboardinterface.h
- dde-clipboard-daemon/wlrintegration/wlrdatacontroldeviceintegration.cpp
- dde-clipboard-daemon/wlrintegration/wlrdatacontroldeviceintegration.h
- dde-clipboard-daemon/wlrintegration/wlrdatacontrolmanagerintegration.cpp
- dde-clipboard-daemon/wlrintegration/wlrdatacontrolmanagerintegration.h
- dde-clipboard-daemon/wlrintegration/wlrdatacontrolofferintegration.cpp
- dde-clipboard-daemon/wlrintegration/wlrdatacontrolofferintegration.h
- dde-clipboard-daemon/wlrintegration/wlrdatacontrolsourceintegration.cpp
- dde-clipboard-daemon/wlrintegration/wlrdatacontrolsourceintegration.h
- dde-clipboard/itemwidget.cpp
- dde-clipboard/mainwindow.h
- dock-clipboard-plugin/clipboarditem.cpp
- dock-clipboard-plugin/clipboardplugin.cpp
as title
Log: as title
Task: https://pms.uniontech.com/task-view-367947.html
> chore: refactor unreasonable places

- debian/changelog
> chore: bump to 1:6.1.1

- .reuse/dep5
- debian/changelog
release 1:6.1.3
Log: bump version to 1:6.1.3
> chore: bump version to 1:6.1.3

- debian/changelog
> chore: bump version to 1:6.1.4

- misc/dde-clipboard-daemon.service.in
- misc/dde-clipboard.service.in
> feat: add restart when failed

- debian/changelog
> chore: bump version to 1:6.1.6
